Member.create([
  { :name => "김재영", :role_id => 1 },
  { :name => "박대현", :role_id => 1 },
  { :name => "김동은", :role_id => 2 },
  { :name => "정하림", :role_id => 2 },
  { :name => "신한솔", :role_id => 2 },
  { :name => "김재연", :role_id => 1 },
  { :name => "이람", :role_id => 2 },
  { :name => "권동현", :role_id => 1 },
  { :name => "김도윤", :role_id => 1 },
  { :name => "김성진", :role_id => 1 },
  { :name => "김성환", :role_id => 3 },
  { :name => "김소윤", :role_id => 1 },
  { :name => "박선영", :role_id => 1 },
  { :name => "박세희", :role_id => 2 },
  { :name => "박수빈", :role_id => 1 },
  { :name => "박준회", :role_id => 1 },
  { :name => "박지현", :role_id => 1 },
  { :name => "서계원", :role_id => 1 },
  { :name => "송아미", :role_id => 2 },
  { :name => "송주연", :role_id => 2 },
  { :name => "신문규", :role_id => 1 },
  { :name => "김승원", :role_id => 3 },
  { :name => "안선영", :role_id => 2 },
  { :name => "안성호", :role_id => 3 },
  { :name => "오승목", :role_id => 1 },
  { :name => "오혜린", :role_id => 2 },
  { :name => "유지민", :role_id => 2 },
  { :name => "윤현구", :role_id => 1 },
  { :name => "이수민", :role_id => 1 },
  { :name => "이수완", :role_id => 1 },
  { :name => "이은숙", :role_id => 1 },
  { :name => "이재환", :role_id => 3 },
  { :name => "이한솔", :role_id => 1 },
  { :name => "이현진", :role_id => 1 },
  { :name => "임주현", :role_id => 1 },
  { :name => "임희조", :role_id => 1 },
  { :name => "장현철", :role_id => 3 },
  { :name => "장혜정", :role_id => 2 },
  { :name => "전혜성", :role_id => 1 },
  { :name => "정다운", :role_id => 1 },
  { :name => "조예지", :role_id => 2 },
  { :name => "홍주영", :role_id => 3 },
  { :name => "김유리", :role_id => 2 },
  { :name => "정보배", :role_id => 1 }
], :without_protection => true )

Category.create([
  { :name => "프로그래밍"},
  { :name => "디자인"},
  { :name => "자기개발서"},
  { :name => "어학공부"}
], :without_protection => true )

Book.create([
  { :title=>"GOF 디자인 패턴", :author=>"에릭 감마", :description=>"디자인패턴 책입니다.",
    :img=>File.new("#{Rails.root}/public/image/gof.jpg"),
    :member_id=>1, :category_id=>1},
    { :title=>"HEAD FIRST PYTHON", :author=>"폴 배리", :description=>"Python 책입니다.",
    :img=>File.new("#{Rails.root}/public/image/head_first_python.jpg"),
    :member_id=>1, :category_id=>1},
    { :title=>"os 구조와 원리", :author=>"카와이 히데미", :description=>"os 만들기 유명한책",
    :img=>File.new("#{Rails.root}/public/image/os_make.jpg"),
    :member_id=>1, :category_id=>1},
    { :title=>"안드로이드 프로그래밍 정복 1", :author=>"김상형", :description=>"안드로이드 그책 맞아요",
    :img=>File.new("#{Rails.root}/public/image/android_1.jpg"),
    :member_id=>1, :category_id=>1},
    { :title=>"안드로이드 프로그래밍 정복 2", :author=>"김상형", :description=>"안드로이드 그책 맞아요",
    :img=>File.new("#{Rails.root}/public/image/android_2.jpg"),
    :member_id=>1, :category_id=>1},
    { :title=>"JQuery Cookbook", :author=>"김경훈", :description=>"JQuery 1.x 대 책이라...",
    :img=>File.new("#{Rails.root}/public/image/jquery_cookbook.jpg"),
    :member_id=>1, :category_id=>1},
    { :title=>"Effective C++", :author=>"스콧 마이어스", :description=>"스콧 마이어스 C++ 고급책 입니다.",
    :img=>File.new("#{Rails.root}/public/image/effect_c++.jpg"),
    :member_id=>1, :category_id=>1}
], :without_protection => true )